Traceback (most recent call last):
  File "C:\Users\Administrator\esp\v5.3.3\esp-idf\tools\kconfig_new\prepare_kconfig_files.py", line 102, in <module>
    main()
  File "C:\Users\Administrator\esp\v5.3.3\esp-idf\tools\kconfig_new\prepare_kconfig_files.py", line 98, in main
    _prepare_source_files(env, list_separator)
  File "C:\Users\Administrator\esp\v5.3.3\esp-idf\tools\kconfig_new\prepare_kconfig_files.py", line 64, in _prepare_source_files
    _write_source_file(env_dict['COMPONENT_KCONFIGS'], env_dict['COMPONENT_KCONFIGS_SOURCE_FILE'])
  File "C:\Users\Administrator\esp\v5.3.3\esp-idf\tools\kconfig_new\prepare_kconfig_files.py", line 60, in _write_source_file
    with open(config_file, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:/椤圭洰鏂囦欢/esp32/ai-xiaozhi/DOIT_AI/build/kconfigs.in'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\.espressif\python_env\idf5.3_py3.11_env\Lib\site-packages\kconfgen\__main__.py", line 18, in <module>
    main()
  File "C:\Users\Administrator\.espressif\python_env\idf5.3_py3.11_env\Lib\site-packages\kconfgen\core.py", line 717, in main
    config = kconfiglib.Kconfig(args.kconfig, parser_version=parser_version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.espressif\python_env\idf5.3_py3.11_env\Lib\site-packages\kconfiglib\core.py", line 920, in __init__
    self()
  File "C:\Users\Administrator\.espressif\python_env\idf5.3_py3.11_env\Lib\site-packages\kconfiglib\core.py", line 934, in __call__
    prev = self._parse_block(None, self.top_node, self.top_node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.espressif\python_env\idf5.3_py3.11_env\Lib\site-packages\kconfiglib\core.py", line 2566, in _parse_block
    raise KconfigError(
kconfiglib.core.KconfigError: C:/Users/Administrator/esp/v5.3.3/esp-idf/Kconfig:336: 'D:/椤圭洰鏂囦欢/esp32/ai-xiaozhi/DOIT_AI/build/kconfigs_projbuild.in' not found (in 'source "$COMPONENT_KCONFIGS_PROJBUILD_SOURCE_FILE"'). Check that environment variables are set correctly (e.g. $srctree, which is unset or blank). Also note that unset environment variables expand to the empty string.
CMake Error at C:/Users/Administrator/esp/v5.3.3/esp-idf/tools/cmake/kconfig.cmake:209 (message):
  Failed to run kconfgen
  (C:/Users/Administrator/.espressif/python_env/idf5.3_py3.11_env/Scripts/python.exe;-m;kconfgen;--list-separator=semicolon;--kconfig;C:/Users/Administrator/esp/v5.3.3/esp-idf/Kconfig;--sdkconfig-rename;C:/Users/Administrator/esp/v5.3.3/esp-idf/sdkconfig.rename;--config;D:/项目文件/esp32/ai-xiaozhi/DOIT_AI/sdkconfig;--defaults;D:/项目文件/esp32/ai-xiaozhi/DOIT_AI/sdkconfig.defaults;--env-file;D:/项目文件/esp32/ai-xiaozhi/DOIT_AI/build/config.env).
  Error 1
Call Stack (most recent call first):
  C:/Users/Administrator/esp/v5.3.3/esp-idf/tools/cmake/build.cmake:643 (__kconfig_generate_config)
  C:/Users/Administrator/esp/v5.3.3/esp-idf/tools/cmake/project.cmake:717 (idf_build_process)
  CMakeLists.txt:13 (project)


